#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <terry.yinzhe@gmail.com> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return to Terry Yin.
#
# The idea of this is borrowed from <mort.yao@gmail.com>'s brilliant work
#    https://github.com/soimort/google-translate-cli
# He uses "THE BEER-WARE LICENSE". That's why I use it too. So you can buy him a 
# beer too.
# ----------------------------------------------------------------------------
'''
This is a simple, yet powerful command line translator with google translate
in behind.
'''
from translate import Translator
import sys
import locale

def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('texts', metavar='text', nargs='+',
                   help='a string to translate(use "" when it\'s a sentence)')
    args = parser.parse_args()
    translator= Translator(to_lang="zh")
    translation = translator.translate(args.texts[0])
    if sys.version_info.major == 2:
        translation =translation.encode(locale.getpreferredencoding())
    sys.stdout.write(translation)
    sys.stdout.write("\n")

if __name__ == "__main__":
    main()
